export const GET_MANAGER_INFO_REQUEST = "GET_MANAGER_INFO_REQUEST";
export const GET_MANAGER_INFO_SUCCESS = "GET_MANAGER_INFO_SUCCESS";
export const GET_MANAGER_INFO_FAILURE = "GET_MANAGER_INFO_FAILURE";

export const GET_MANAGER_REPORT_REQUEST = "GET_MANAGER_REPORT_REQUEST";
export const GET_MANAGER_REPORT_SUCCESS = "GET_MANAGER_REPORT_SUCCESS";
export const GET_MANAGER_REPORT_FAILURE = "GET_MANAGER_REPORT_FAILURE";

export const GET_MANAGER_VIDEOS_REQUEST = "GET_MANAGER_VIDEOS_REQUEST";
export const GET_MANAGER_VIDEOS_SUCCESS = "GET_MANAGER_VIDEOS_SUCCESS";
export const GET_MANAGER_VIDEOS_FAILURE = "GET_MANAGER_VIDEOS_FAILURE";


